# -*- coding: utf-8 -*-
"""ai_ders_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eb02aE4Zbr8_by7cijstqrKkFvIPOnxe

*24.10.2024 *- IGU MYO BILGISAYAR TEKNOLOJISI PROGRAMI AI DERSI (4.Hafta )
"""

import sys
print(sys.version)

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/Ai_Ders_IGU_2024')
!pwd

"""## CPU (Central Process Unit):
Sunucudaki temel bilgi işlem birimi olan donanım bileşenidir.Bellekten talimatları getirir, gerekli görevleri gerçekleştirir ve çıktıyı belleğe geri gönderir. İşletim sistemini ve uygulamaları çalıştırmak için gereken tüm bilgi işlem görevlerini yerine getirir.
## GPU (Graphics Processing Unit):
 Grafik işlemci birimi diye adlandırılan, anakart veya ekran kartı üzerinde bulunan grafik oluşturmakla görevli olan özel bir işlemci birimidir.Üzerinde bulunan çok sayıda çekirdek sayesinde görüntü oluşturmak ve karmaşık matematiksel işlemler yapmak ve tekrarlanan görevleri tamamlamak üzere sınıflanmıştır.
## GPU ve CPU Arasındaki Farklar Nelerdir?
- CPU, GPU’ya nazaran daha fazla bellek tüketir.
- CPU seri komutları işlemekte yeteneklidir, GPU ise paralel komutları işlemekte daha iyidir.
- CPU, GPU’ya nazaran daha yavaştır.
- Çekirdek sayısı CPU’da 10 lu rakamlarda olabilirken, GPU’da 40.000 kadar çekirdek olabilmektedir.
- CPU düşük gecikme, GPU ise yüksek verime odaklanmıştır.

### *GPU sadece tek bir işlem yapmakta, yani görüntü işlemekte iyidir. CPU yavaştır ancak çok sayıda zorlu görevin altından kalkabilir, GPU’yu ise çok sayıda işçisi olan ve tek bir ürün çıkaran bir fabrikaya benzetilebilir.*
"""

## -- CPU ve GPU teknolojisinin kullanımına göre olması gereken veri sayısı tablosu

import pandas as pd

tablo = {
    "Aralık": ["Küçük ölçekli", "Orta ölçekli", "Büyük ölçekli", "Hiper ölçekli", "Exascale"],
    "Veri Sayısı": ["100 - 10,000", "10,000 - 100,000", "100,000 - Milyon",  "Milyon - Milyar", "Milyar - Trilyon"],
    "CPU": ["Evet", "Evet", "Opsiyonel", "Hayır", "Hayır"],
    "GPU": ["Hayır", "Opsiyonel", "Evet", "Evet", "Evet"]
}

print(pd.DataFrame(tablo))

"""### Kütüphane Kurulumunda dikkat edilmesi gereken en önemli konu:
Genel kullanım bakımından python kütüphanesi kurucağımız zaman dikkat edilmesi gereken iki yapı bulunmaktadır. Bu yapılar "pip" ve "pip3"'tür.

pip yapısı -> Python 2.x sürümlerini destekler.

pip3 yapısı -> Python 3.x sürümlerini destekler.

# Karmaşıklık Matrisinden, sistemin doğruluğunu bulacağımız formül

- Dogruluk = TP+TN+FP+FN / TP+TN 'dir.

Örneğin: TP = 50, TN = 40, FP = 5, FN = 5 ise; Dogruluk = 50 + 40 + 5 + 5 / 50 + 40 --> 0.9 -> % 90 olarak hesaplanmaktadır.

%90 Model Doğruluk Oranı - %10 Modelin Hata Oranı 'dır.

### Hata oranını azaltmak için

-*Modelin iyileştirilmesi*

-*Veri sayısının arttırılması*

-*Eğitim adım sayısının değiştirilmesi*

-*Veri seti içerisindeki farklı değişlenlerin - özelliklerin algoritmaya dahil edilmesi.*
"""

import pandas as pd

## -- Doğru Pozitif (TP), Doğru Negatif (TN), Yanlış Pozitif (FP), Yanlış Negatif (FN)
matris_bilgisi = {
    "Real Positive": ["True Positive (TP)", "False Negative (FN)"],
    "Real Negative": ["False Positive (FP)", "True Negative (TN)"]
}

## -- DataFrame oluşturma
matris = pd.DataFrame(matris_bilgisi, index=["Forecast Positive", "Forecast Negative"])

## -- Tabloyu gösterme
print(matris)

"""# Scikit-Learn<>"""

!pip install -U scikit-learn ## -- scikit-learn kütüphanesinin dahil edilmesi ve veri setinin işleme alınması

from sklearn.datasets import fetch_california_housing ## -- Kaliforniya'daki konut verilerini içeren bir veri setini yükler. Scikit-learn kütüphanesinden bir fonksiyondur
import pandas as pd

housing = fetch_california_housing() ## -- California Housing veri setini yükleme

## -- Özellikleri ve hedef değişkeni almak
X = housing.data  ## -- Bağımsız değişkenler (özellikler)
y = housing.target  ## -- Bağımlı değişken (fiyatlar)

## -- Verileri bir DataFrame'e dönüştürme
df = pd.DataFrame(X, columns=housing.feature_names)
df['PRICE'] = y

print(df.head()) ## -- İlk birkaç satırı görüntüleme

"""#### cpu-gpu açıklaması için kullanılan bilgi link : https://www.hosting.com.tr/bilgi-bankasi/gpu-nedir/"""